### NumPy Array And Basics

In [2]:
import numpy as np

### Creating Array with List

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [4]:
py_list = [1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication 
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


### Creating Array from Scratch

In [5]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("Ones array: \n", ones)

full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.60682199 0.45392664 0.71771504]
 [0.24473508 0.49032226 0.93084746]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties:-

In [7]:
arr = np.array([[1,2,3],
                [4,5,6,]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DataType:", arr.dtype)


Shape: (2, 3)
Dimension: 2
Size: 6
DataType: int64


### Array Reshaping

In [8]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel(returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array ", flattened)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

# Another method for transpose
transposed = reshaped.transpose()
print("\n Transposed array ", transposed)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## NumPy Array Operation

In [11]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])

print("With Step", arr[1:8:2]) # using step

print("Negative indexing", arr[-3]) # using negative indexing

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [14]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2]) # For a specific ele in array

print("Entire row: ", arr_2d[1]) # For targeting row in array

print("Entire Col: ", arr_2d[:, 1]) # For targeting col in array

Specific element 6
Entire row:  [4 5 6]
Entire Col:  [2 5 8]


### Sorting

In [20]:
unsorted = np.array([3, 1, 4, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1, 2], [2, 3]])
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 2 3 4 5 6 9]
Sorted 2D array by row [[1 1]
 [2 2]
 [3 3]]


### Filter

In [22]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


#### Filter with mask

In [23]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


#### Fancy indexing vs np.where

In [25]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [26]:
condition_array = np.where(numbers > 5)
print(condition_array)

(array([5, 6, 7, 8, 9]),)


In [28]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removing Data

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


In [30]:
# Array compatiblity

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [33]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column",with_new_col)

[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [36]:
# Delete

arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5]
